In [1]:
import numpy as np
arr = np.array(42)
print(arr)

42


In [3]:
import numpy as np 
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[1,2,3]])
print(arr)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [12]:
import numpy as np 
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6,]])
d = np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
2


In [13]:
import numpy as np
arr = np.array([1,2,3,4])import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])
print(arr[3])import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:3])

4
