In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])#index 1 to 4 
print(arr[:5])# index 0 o 4
print(arr[:])

[2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5 6 7]


In [6]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [9]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:3])

[2 5]


In [10]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]
